### PR TITLE
Initial design for LRS-350-12 Meanwell Power Supply cover. 

### PR DESCRIPTION
**Pull request by ChinookTx**
Use stock socket, switch and wires.  No logo.

### CODE REVIEW

**Comment by rob5standingby** [comment]
@pcbroch This looks good, but will need to test it :)

**Comment by JohnOCFII** [comment]
This has been test-fit by at least 3 Haribros, including myself.  I think it can get promoted to the correct place.  "Optional?"

**Comment by JohnOCFII** [comment]
As mentioned on Slack - I'd request the hole for the cables be made larger (or Joseph suggested additional holes) to hold larger diameter cables and/or additional cables.  I'd suggest making the opening twice as tall and twice as wide (or two holes with similar total opening space).

**Comment by rob5standingby** [comment]
Noted @JohnOCFII . Making an "Issue" with your notes.

**Pull request merged**
