### PR TITLE
Simplifies/clarifies BOM instructions. Adds CSV helpers.

### PR DESCRIPTION
**Pull request by rob5standingby**
# Why?
There are two main things that this PR attempts to accomplish:
1. **Simplify the BOM**. Make it EXTREMELY clear for users who are simply upgrading their existing MK2 what they need to build a Haribo.
2. **ADDS Pre-Built CSV Files and Instructions for Misumi** No more asking "Am I ordering everything correctly?" There is now a pre-built guide for either black or silver (regular extrusions). The user can pick one and upload it using the instructions and buy all the required parts needed. Eliminate the guesswork.

### CODE REVIEW

**Comment by JohnOCFII** [comment]
Rob,

I tried looking through this, but either I'm not seeing everything, or it doesn't actually show everything.  Ideally, for the Misumi order, you would have the color selection (can you add yellow too?) then the T-nuts from Misumi, the feet, etc.  I don't see those other bits from Misumi.  I see some non-functional links to CSV files, but ideally you would show a (nicely formatted) version of what is in those CSV files too.

Next bit would be to separate the hardware into similar sections: A) Everyone needs these bits (frame hardware) and B) You need these bits if you aren't moving hardware from your MK2.

**Comment by rob5standingby** [comment]
@JohnOCFII Can you take another look? I've just pushed up some major changes to the list. I believe it's much simpler to follow now, and I've added links to parts where applicable.

**Comment by rob5standingby** [comment]
I'm not going to bother with adding part numbers for anything other than silver / black for now. I think if folks are aware of the process they can start to deviate. I want to keep things simple and streamlined for now.

**Comment by ryanneufeld** [comment]
This repo needs a .gitignore file, and it should have `.DS_Store` as an entry in it.

**Comment by rob5standingby** [comment]
@ryanneufeld Oops...I didn't see that. Adding.

**Comment by rob5standingby** [comment]
@ryanneufeld @JohnOCFII Let me know what you think now

**Comment by JohnOCFII** [comment]
I like the flow.  As of now (unless I'm not seeing it when I review changes) the Misumi order is just showing the aluminum option and not the black option.  

Do you want to tackle "optional" stuff at this point?  For example, based on @jtktam's testing, the MK2 PSU will be underpowered above 60 mm/sec at higher temps.  Also, he has concerns about the 30W heater.  I see you have the Meanwell under the build from scratch list, where it also makes sense.  

But as you say - maybe we should launch what you have, and fine tune from there. :)

**Comment by rob5standingby** [comment]
@JohnOCFII Let's add in `optional` stuff on a second PR! You're right about the PSU stuff. Let me see if I can get @jtktam to weigh in on this PR any :)

**Pull request merged**
